### ISSUE TITLE
Item pubdate being formatted twice

### ISSUE THREAD

**Issue by dvatp** [RoumenDamianoff/laravel-feed#23]
While calling:
    setDateFormat('timestamp')
    add() with a pubdate in unix timestamp for each item
the method
    render('rss')
results in an error:
    "A non well formed numeric value encountered"
I traced the error and discovered that you're calling formatDate() during add(), and then again in render() within the ($format == 'rss') branch.  This causes the conversion (in my case) from a unix timestamp (e.g. 1421271506) to a rss-compatible date string (e.g. 2015-01-11T18:10:11+00:00) first in add() and then again in render().  The second call naturally fails, since it's expecting an integer and it gets a string.
I can eliminate the error by merely commenting out the call to formatDate in render() or work around the problem by calling render() with no arguments, thus defaulting to atom format and avoiding that logic branch.  As it turns out I'll probably use atom because it allows tags within the description of an item vs. rss that apparently calls strip_tags, but I figured I'd bring up this error in rss mode.

**Comment by jrubins** [comment]
There's an issue with the update made to address this.

If I'm rendering the feed in RSS format, the pubdate for the entire RSS feed is in a different format than the pubdate for each individual item and there's no way to get a consistent date format for the two. 

This happens because the `add` method does not accept a format ("rss" or "atom") so when the `formatDate` method is called from within the `add` method, the default format of "atom" is always used.

```
public function add($title, $author, $link, $pubdate, $description, $content='', $enclosure = array()) {
    // Other stuff

    // The following line is the issue since there's no way to specify a format of 
    // "rss" to the "formatDate" method.
    $pubdate = $this->formatDate($pubdate);

    // Other stuff
}
```

**Comment by jrubins** [comment]
Thanks for the update @RoumenDamianoff. Could this be updated in the Laravel 4 branch and could new tags be created as well? (My project is using the 2.8.* branch for Laravel 4.)

**Comment by RoumenDamianoff** [comment]
Yes, this fix is already ported to laravel4 branch and will be in the next version.
