### ISSUE TITLE
Cache and custom views

### ISSUE THREAD

**Issue by Thorn-workshop** [RoumenDamianoff/laravel-feed#27]
Don't cache custom views because:
line_165: Cache::put($this->cacheKey, View::make('feed::'.$format ...

**Comment by RoumenDamianoff** [comment]
Is the customView field set correctly and is the view file exists (with the same name)?

**Comment by Thorn-workshop** [comment]
Yes, it exists and properly render in case without cache.
"View::make" trying to find templates only at its own path by hint 'feed::', while custom template are located at custom path.

**Comment by RoumenDamianoff** [comment]
Can you test and confirm that with latest commit this problem is fixed?

**Comment by Thorn-workshop** [comment]
I am afraid, no. I am using version 2.8 for Laravel 4.2

**Comment by RoumenDamianoff** [comment]
Try with version 2.8.2 (or dev-laravel4), updates are ported to it.
