### ISSUE TITLE
Link in channel should be link to site, not feed file

### ISSUE THREAD

**Issue by Alroniks** [RoumenDamianoff/laravel-feed#35]
Please, see https://validator.w3.org/feed/docs/rss2.html

Now it works that:
```xml
<link>http://example.com/rss.xml</link>
<atom:link href="http://example.com" rel="self" />
```

Expected:
```xml
<link>http://example.com/</link>
<atom:link href="http://example.com/rss.xml" rel="self" />
```

**Comment by Ostendorf** [comment]
I was just about to say the same, but there is more to this.
Two variables need to be swapped.

In rss.blade:
`<link>{{ $channel['link'] }}</link>`
`<atom:link href="{{ Request::url() }}" rel="self"></atom:link>`

should be:
`<link>{{ Request::url() }}</link>`
`<atom:link href="{{ $channel['link'] }}" rel="self"></atom:link>`

**Comment by Alroniks** [comment]
Created PR with fix @Ostendorf @RoumenDamianoff

**Comment by Alroniks** [comment]
PR merged, so close
