### ISSUE TITLE
Update 'Content-type' response header to be 'Content-Type'

### ISSUE THREAD

**Issue by jrubins** [RoumenDamianoff/laravel-feed#43]
Just a small update to make the 'Content-type' response header conform to the [specification](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html). It looks like it should be 'Content-Type' (capital 'T').

Specifically I'm looking at the following lines in the `Roumen/Feed/Feed.php` class (v2.8.5):
```
return Response::make(Cache::get($this->cacheKey), 200, array('Content-type' => $this->ctype.'; charset='.$this->charset)); // line 140

return Response::make(Cache::get($this->cacheKey), 200, array('Content-type' => $this->ctype.'; charset='.$this->charset)); // line 183

return Response::make(View::make($this->getView($format), $viewData), 200, array('Content-type' => $this->ctype.'; charset='.$this->charset)); // line 190
```

**Comment by RoumenDamianoff** [comment]
Hi, this change is done in the master and laravel4 branches and soon in the next releases.
