### ISSUE TITLE
Proposal: Allow HTML in the description for a feed item

### ISSUE THREAD

**Issue by jrubins** [RoumenDamianoff/laravel-feed#44]
Currently there's no way to include HTML in a description for a feed item. The `render` method in `Roumen\Feed\Feed.php` strips out HTML tags on line 167 (v2.8.5).

However, HTML in the description is valid per the [RSS 2.0 specification](http://cyber.law.harvard.edu/rss/encodingDescriptions.html). This StackOverflow post lists a couple of ways to properly include HTML in the description field (either escaping the entities or by using CDATA): http://stackoverflow.com/questions/9866472/rss-specification-html-code-inside-rss-feed.

This proposal is to modify the render method to allow HTML in the description field.

**Comment by RoumenDamianoff** [comment]
Hi, Jonathan 

Thank you for this proposal! You are right, html should be allowed in the description tag, also I found out that html shouldn't be used in the title tags by the specification. I made some small updates in the master and laravel4 branches, you could test if you want.

**Comment by cmgmyr** [comment]
:+1:
