### ISSUE TITLE
Multiple Feeds = Supported / Example?

### ISSUE THREAD

**Issue by superdummy** [RoumenDamianoff/laravel-feed#45]
First of all and most important: Thanks for the absolutely great and helpfull Package! 

Well I also have a question. Is my assumption correct, that you can have without any problems multiple Feeds by just calling multiple time the make method?
`feedNews = Feed::make()`
`feedJobs = Feed::make()`
making shure that one uses a **different(!) Cache Key** for both. Then I can render both in the Header?

Just as an Idea for improvement: Maybe this could be added in the example before the "Feed::make()" in the comment as a short notice, that multiple feeds are supported. 

Thanks!

**Comment by RoumenDamianoff** [comment]
Hi, thanks for your advice I added example for multiple feeds in the [wiki](https://github.com/RoumenDamianoff/laravel-feed/wiki/Multiple-Feeds). This is supported from long time, but wasn't explained well in the examples.
