### ISSUE TITLE
Add category to my feed 

### ISSUE THREAD

**Issue by kossa** [RoumenDamianoff/laravel-feed#50]
Hi,

Im working with Laravel, I want to add "category" to my feed (as tag and not in enclosure) to build the same rss here : http://www.lexpressiondz.com/feed/edito/index.1.rss

Thanks

![image](https://cloud.githubusercontent.com/assets/1175584/15096862/a50afc1e-1501-11e6-8cc2-255342054ef5.png)

**Comment by RoumenDamianoff** [comment]
Hi, this is added in the latest version v2.10.2, and now you can add category tag as 8-th param to ``$feed->add() `` or using 'category' key with ``$feed->addItem()``

**Comment by kossa** [comment]
8-th param to $feed->add() works well, but when I use $feed->addItem(['category' => 'something]) not works
