### ISSUE TITLE
No hint path defined for [feed].

### ISSUE THREAD

**Issue by affinitycloud** [RoumenDamianoff/laravel-feed#51]
Using Laravel 5.2 with the following code to generate the feed and receiving:

_No hint path defined for [feed]._

    public function feed()
    {
        $feed = new Feed;
        $feed->setCache(60);

        if ( ! $feed->isCached()) {
            $posts = $this->post->whereNotNull('published_at')->orderBy('published_at', 'desc')->get();

            foreach ($posts as $post) {
                $feed->add($post->meta_title, $post->author(), url($post->slug), $post->published_at, $post->excerpt, $post->content);
            }
        }

        return $feed->render('rss');
    }

**Comment by RoumenDamianoff** [comment]
HI, I can't replicate this error on laravel 5.2 with latest package version. 

Did you add ``use Feed;`` in your controller? Did you add ``Roumen\Feed\FeedServiceProvider::class`` to your service providers and ``'Feed' => Roumen\Feed\Feed::class`` to your aliases in your ``config/app.php``? Did you run ``composer dump-autoload`` after this?

**Comment by sdebacker** [comment]
I also have this problem. I will investigate more on this when I have some time.

**Comment by aygee** [comment]
FeedServiceProvider is deferred by default. You will need to call `App::make('feed')` instead of `new Feed`,  `App::make('feed')` will load the FeedServiceProvider which will register the views for feed.

**Comment by dvatp** [comment]
Had this problem while transitioning an app from 4.2 to 5.2.  aygee's solution is correct.
