### ISSUE TITLE
Titles with "&" invalidates XML (atom)

### ISSUE THREAD

**Issue by nivv** [RoumenDamianoff/laravel-feed#52]
Thanks for a great package, been using it for while.

However, if your title has a `&` it should be transformed to a HTML-entity like `&amp;`. I've tried doing this myself by doing like below:

```php
$feed->add(htmlentities($post->title), $post->author, URL::to('/nyheter/' . Carbon::parse($post->published_at)->toDateString() . '/' . Str::slug($post->title)), $post->published_at, $body);
```
However the output is still containing the `&` as in `Check out our new & awesome stuff` instead of the desired `Check out our new &amp; awesome stuff`.

Any suggestions?

This line is the culprit by the way.
https://github.com/RoumenDamianoff/laravel-feed/blob/master/src/Roumen/Feed/Feed.php#L231

**Comment by jbrooksuk** [comment]
This happens for RSS too, not just Atom.

**Comment by nivv** [comment]
Thanks for a quick fix @jbrooksuk Will this get merged into the L4 branch too?

**Comment by RoumenDamianoff** [comment]
This fix is ported to laravel4 branch and tagged as v2.8.8
