### ISSUE TITLE
CDATA tags need to be used in the title

### ISSUE THREAD

**Issue by jbrooksuk** [RoumenDamianoff/laravel-feed#59]
https://github.com/CachetHQ/Cachet/issues/1973

**Comment by jbrooksuk** [comment]
@RoumenDamianoff can you release a new version so I can get Cachet fixed please?

**Comment by RoumenDamianoff** [comment]
@jbrooksuk yes [v2.10.4](https://github.com/RoumenDamianoff/laravel-feed/releases/tag/v2.10.4) is released.
